datatables:

  # Load i18n data from DataTables CDN or locally
  language_from_cdn:    true

  # Default HTTP method to be used for callbacks
  method:               POST # One of "GET"; "POST"

  # Default options to load into DataTables
  options:
    searching: true
    lengthMenu : [5, 10, 25, 50, 100]
    pageLength:           5
    dom: "<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>><'row'<'col-sm-12'tr>><'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>"


  # Where to persist the current table state automatically
  persist_state:        fragment # One of "none"; "query"; "fragment"; "local"; "session"

  # Default service used to render templates, built-in TwigRenderer uses global Twig environment
  renderer:             Omines\DataTablesBundle\Twig\TwigRenderer

  # Default template to be used for DataTables HTML
  template:             '@DataTables/datatable_html.html.twig'

  # Default parameters to be passed to the template
  template_parameters:

    # Default class attribute to apply to the root table element
    className:        'table table-striped table-bordered table-hover data-table'

    # If and where to enable the DataTables Filter module
    columnFilter:     thead # One of "thead"; "tfoot"; "both"; null

  # Default translation domain to be used
  translation_domain:   forms