index:
  path: /
  controller: App\Controller\HomeController::index
login:
  path: /login
  controller: App\Controller\SecurityController::login
logout:
    path: /logout
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# AppBundle/Resources/config/routing/person.yml

#appel ajax de la liste des contact par prospect
prospect_list_contacts:
    path: /get-contact-from-prospect
    controller: App\Controller\AppointmentController::listCallsByProspect
    methods:  GET
#appel ajax de la liste des appels par prospect
prospect_list_calls:
  path: /get-calls-form-prospect
  controller: App\Controller\AppointmentController::listCallsByProspect
  methods:  GET


