index:
  path: /
  controller: App\Controller\HomeController::index
login:
  path: /login
  controller: App\Controller\SecurityController::login
logout:
    path: /logout
#user
user_index:
    path: /user/
    controller: App\Controller\UserController::index

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
