index:
  path: /
  controller: App\Controller\HomeController::index
login:
  path: /login
  controller: App\Controller\SecurityController::login
logout:
    path: /logout
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# AppBundle/Resources/config/routing/person.yml
prospect_list_contacts:
    path: /get-contact-from-prospect
    controller: App\Controller\ProspectController::listContactByProspect
    methods:  GET
